### ISSUE TITLE
add support for importing keys via wkd

### ISSUE THREAD

**Issue by mfinelli** [netson/ansible-gpg-key#6]
Hi, thanks for this great module. Is there any interest in adding support for importing keys via wkd instead of from a keyserver? Since some time high profile projects are moving their keys to wkd because they're otherwise being spammed by signatures. Importing them via gnupg is relatively straightforward: e.g.,

```
gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org
```

Would it be possible to add support for importing keys in this manner with this module?

**Comment by netson** [comment]
I'll have to do a bit of reading on the WKD/WKS principle, but it does seem like a useful addition! :-)
Obviously I'm open to PR's as well, in case you get around to it sooner, but it's on my radar now and hopefully the summer months will leave some time on my schedule to look into this!

**Comment by netson** [comment]
So obviously the summer months of 2021 did not provide time to do this and I have no need for it. I'm open to PR's, but won't be spending any time on this myself.
