### ISSUE TITLE
Using fingerprint in lower case will set state to changed

### ISSUE THREAD

**Issue by ckotte** [netson/ansible-gpg-key#8]
I already have the key imported, but when I use e.g. `06a26d531d56c42d66805049c5469996f0df68ec` instead of `06A26D531D56C42D66805049C5469996F0DF68EC`, the task will always be in changed state.

**Comment by netson** [comment]
Hi, thanks for the feedback; should be fixed with the latest commit:  83c0eb2649dd87254fc91f40361bca84e5b199f6
